config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'en', to: "pages#en"
  resources :trainers, only: [:new, :show, :index]

  resources :contacts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  after_create :send_contact_email

  private

  def send_contact_email
    ContactMailer.contact_mail(self).deliver_now
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :trainer
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :trainer
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :offers
  has_many :reviews

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver

      redirect_to root_path
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @contact = Contact.new
    @trainers = Trainer.all
  end

  def en
    @contact = Contact.new
    @trainers = Trainer.all
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]
  before_action :liste_of_specialities, only: :show


  def index
    if params[:address].present?
      @trainers = Trainer.near(params[:address])
    else
      @trainers = Trainer.all
    end
  end

  def show
  end

  def new
    @trainer = Trainer.new
  end

  def edit
  end

  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:city, :description, :email, :phone, :name, :surname, :photo, :photo_cache, :specialities)
    end

    def liste_of_specialities
      @liste = @trainer.specialities.scan(/\w+/)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Venga - A perfect workout, just like you !</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="Venga connects you with personal trainers offering unique sport experiences in Brussels. It's time to enjoy your workout ! ">

    <meta property=“og:title” content=“Venga - A perfect workout, just like you.”>
    <meta property="og:type" content="www.be-venga.com" />
    <meta property="og:url" content="http://www.be-venga.com" />
    <meta property=“og:image” content=“metavenga.png”>
    <meta property=“og:description” content=“Venga connects you with personal trainers offering unique sport experiences in Brussels. It's time to enjoy your workout !”>
    <meta property="og:site_name" content="Venga" />
    <meta name="google-site-verification" content="auNpT9NLbOWk-7Q8a1SZeGqwtIH97ukOtMDGutlsT_4" />

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>

  <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.8&appId=1845234315688643";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>

    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?signed_in=true&libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= yield(:after_js) %>
  </body>


    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-89250384-1', 'auto');
  ga('send', 'pageview');
  </script>

</html>

app/views/pages/thankyou.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google-site-verification" content="auNpT9NLbOWk-7Q8a1SZeGqwtIH97ukOtMDGutlsT_4" />
    <meta name="description" content="Venga connects sporties with personal trainers offering unique sport experiences in Brussels. It's time to enjoy your workout ! ">
    <title>Venga - Find your personal trainer in Brussels !</title>
  </head>

  <body>
    <div class="banner">
      <div class="banner-content">
        <h1>WELCOME VENGY !</h1>
        <p>It's time to enjoy a unique sport experience with your coach.</p>
      </div>
    </div>

    <h3 class="subsub text-center">Your next workout in Brussels</h3>

    <div class="container list-inline">
      <div class="card">
        <div class="card-category">
          <div class=" line1 list-inline">
            <h3>Margaux</h3>
              <div class="flags">
                <%= image_tag("fr.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
                <%= image_tag("en.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
              </div>
          </div>
          <div class="list-inline">
            <%= image_tag("location.png", :alt => "rss feed", :height => "5%", :width => "5%", class: "location") %>
            <p>Brussels (Ganshoren)</p>
          </div>
          <hr class="hr--small">
        </div>

          <div class="price list-inline">
            <%= image_tag("margauxrubi.jpg", :alt => "rss feed", :height => "103%", :width => "35%", class: "picture") %>
            <h4>
            à partir de<br>
            30€ / heure
            </h4>
          </div>

        <div class="card-description">
          <p>Certified personal trainer with 3+ years experience as a fitness coach. Specialised in functional and core muscles training. </p>
          <div class="contact list-inline">
            <p>0478/37.14.95</p>
            <div class="mail"><p>info@margauxrubi.be</p></div>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-category">
          <div class=" line1 list-inline">
            <h3>Tom</h3>
              <div class="flags">
                <%= image_tag("fr.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
                <%= image_tag("en.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
              </div>
          </div>
          <div class="list-inline">
            <%= image_tag("location.png", :alt => "rss feed", :height => "5%", :width => "5%", class: "location") %>
            <p>Brussels (Ixelles)</p>
          </div>
          <hr class="hr--small">
        </div>

          <div class="price list-inline">
            <%= image_tag("tom.png", :alt => "rss feed", :height => "103%", :width => "35%", class: "picture") %>
            <h4>
              à partir de<br>
              40€ / heure
            </h4>
          </div>

        <div class="card-description">
          <p>Certified personal trainer with 3+ years experience as a fitness coach. Specialised in functional and core muscles training. </p>
          <div class="contact list-inline">
            <p>0478/33.09.01</p>
            <div class="mail"><p>odethompson@yahoo.co.uk</p></div>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-category">
          <div class=" line1 list-inline">
            <h3>Nadine</h3>
              <div class="flags">
                <%= image_tag("fr.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
                <%= image_tag("en.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
              </div>
          </div>
          <div class="list-inline">
            <%= image_tag("location.png", :alt => "rss feed", :height => "5%", :width => "5%", class: "location") %>
            <p>Brussels</p>
          </div>
          <hr class="hr--small">
        </div>

          <div class="price list-inline">
            <%= image_tag("Nadine.jpg", :alt => "rss feed", :height => "103%", :width => "35%", class: "picture") %>
            <h4>47€ / hour</h4>
          </div>

        <div class="card-description">
          <p>Certified personal trainer with 3+ years experience as a fitness coach. Specialised in functional and core muscles training. </p>
          <div class="contact list-inline">
            <p>0476/53.05.27 </p>
            <div class="mail"><p>nadine.winterbeek@bc-training.be</p></div>
          </div>
        </div>
      </div>
    </div>

    <div class="container list-inline">
      <div class="card">
        <div class="card-category">
          <div class=" line1 list-inline">
            <h3>Henri-Matthieu</h3>
              <div class="flags">
                <%= image_tag("fr.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
                <%= image_tag("en.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
              </div>
          </div>
          <div class="list-inline">
            <%= image_tag("location.png", :alt => "rss feed", :height => "5%", :width => "5%", class: "location") %>
            <p>Brussels (Woluwe-Saint-Lambert)</p>
          </div>
          <hr class="hr--small">
        </div>

          <div class="price list-inline">
            <%= image_tag("hmf.jpg", :alt => "rss feed", :height => "103%", :width => "35%", class: "picture") %>
            <h4>47€ / hour</h4>
          </div>

        <div class="card-description">
          <p>Certified personal trainer with 3+ years experience as a fitness coach. Specialised in functional and core muscles training. </p>
          <div class="contact list-inline">
            <p>0475/23.72.27 </p>
            <div class="mail"><p>hmfraiture@gmail.com</p></div>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-category">
          <div class=" line1 list-inline">
            <h3>Florence</h3>
              <div class="flags">
                <%= image_tag("fr.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
                <%= image_tag("en.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
              </div>
          </div>
          <div class="list-inline">
            <%= image_tag("location.png", :alt => "rss feed", :height => "5%", :width => "5%", class: "location") %>
            <p>Brussels (Ixelles)</p>
          </div>
          <hr class="hr--small">
        </div>

          <div class="price list-inline">
            <%= image_tag("florence.png", :alt => "rss feed", :height => "140%", :width => "36%", class: "picture") %>
            <h4>47€ / hour</h4>
          </div>

        <div class="card-description">
          <p>Certified personal trainer with 3+ years experience as a fitness coach. Specialised in functional and core muscles training. </p>
          <div class="contact list-inline">
            <p>0473/56.93.87</p>
            <div class="mail"><p>florencesamain@hotmail.com</p></div>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-category">
          <div class=" line1 list-inline">
            <h3>Youssef</h3>
              <div class="flags">
                <%= image_tag("fr.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
                <%= image_tag("en.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
              </div>
          </div>
          <div class="list-inline">
            <%= image_tag("location.png", :alt => "rss feed", :height => "5%", :width => "5%", class: "location") %>
            <p>Brussels (Ixelles)</p>
          </div>
          <hr class="hr--small">
        </div>

          <div class="price list-inline">
            <%= image_tag("youssef.jpg", :alt => "rss feed", :height => "103%", :width => "35%", class: "picture") %>
            <h4>47€ / hour</h4>
          </div>

        <div class="card-description">
          <p>Certified personal trainer with 3+ years experience as a fitness coach. Specialised in functional and core muscles training. </p>
          <div class="contact list-inline">
            <p>0484/41.79.64</p>
            <div class="mail"><p>tycoaching1030@gmail.com</p></div>
          </div>
        </div>
      </div>
    </div>

    <div class="container list-inline">
      <div class="card">
        <div class="card-category">
          <div class=" line1 list-inline">
            <h3>Mounia</h3>
              <div class="flags">
                <%= image_tag("fr.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
                <%= image_tag("en.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
              </div>
          </div>
          <div class="list-inline">
            <%= image_tag("location.png", :alt => "rss feed", :height => "5%", :width => "5%", class: "location") %>
            <p>Brussels (Ixelles)</p>
          </div>
          <hr class="hr--small">
        </div>

          <div class="price list-inline">
            <%= image_tag("mounia.jpg", :alt => "rss feed", :height => "103%", :width => "35%", class: "picture") %>
            <h4>47€ / hour</h4>
          </div>

        <div class="card-description">
          <p>Certified personal trainer with 3+ years experience as a fitness coach. Specialised in functional and core muscles training. </p>
          <div class="contact list-inline">
            <p>0484/61.51.42</p>
            <div class="mail"><p>mouniamiri@yahoo.fr</p></div>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-category">
          <div class=" line1 list-inline">
            <h3>Alex</h3>
              <div class="flags">
                <%= image_tag("fr.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
                <%= image_tag("en.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
              </div>
          </div>
          <div class="list-inline">
            <%= image_tag("location.png", :alt => "rss feed", :height => "5%", :width => "5%", class: "location") %>
            <p>Brussels (Ixelles)</p>
          </div>
          <hr class="hr--small">
        </div>

          <div class="price list-inline">
            <%= image_tag("Alex2.png", :alt => "rss feed", :height => "103%", :width => "35%", class: "picture") %>
            <h4>47€ / hour</h4>
          </div>

        <div class="card-description">
          <p>Certified personal trainer with 3+ years experience as a fitness coach. Specialised in functional and core muscles training. </p>
          <div class="contact list-inline">
            <p>0498/26.58.23</p>
            <div class="mail"><p>alex@gmail.com</p></div>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-category">
          <div class=" line1 list-inline">
            <h3>Alex</h3>
              <div class="flags">
                <%= image_tag("fr.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
                <%= image_tag("en.png", :alt => "rss feed", :height => "40%", :width => "40%", class: "") %>
              </div>
          </div>
          <div class="list-inline">
            <%= image_tag("location.png", :alt => "rss feed", :height => "5%", :width => "5%", class: "location") %>
            <h5>Brussels (Ixelles)</h5>
          </div>
          <hr class="hr--small">
        </div>

          <div class="price list-inline">
            <%= image_tag("Alex2.png", :alt => "rss feed", :height => "103%", :width => "35%", class: "picture") %>
            <h4>47€ / hour</h4>
          </div>

        <div class="card-description">
          <p>Certified personal trainer with 3+ years experience as a fitness coach. Specialised in functional and core muscles training. </p>
          <div class="contact list-inline">
            <p>0498/26.58.23</p>
            <div class="mail"><p>alex@gmail.com</p></div>
          </div>
        </div>
      </div>
    </div>

      <div class="footer list-inline">
        <div class="copyright">
          <p>Copyright @ Venga 2016 - All rights reserved</p>
        </div>
        <div class="infos list-inline">
          <a href="https://www.facebook.com/bevenga">
            <i class="fa fa-facebook hello"></i>
          </a>
          <a href="https://plus.google.com/u/0/112317262085738282278">
            <i class="fa fa-google-plus hello"></i>
          </a>
          <a href="mailto:alexandre.tombeur@gmail.com?subject=Info Venga">
            <i class="fa fa-envelope hello" aria-hidden="true"></i>
          </a>
          <p class="phone">+32(0)498/26.58.23</p>
        </div>

      </div>
    </body>

    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-89250384-1', 'auto');
    ga('send', 'pageview');

    </script>

</html>

app/views/shared/_footer.html.erb
<footer class="footer pt-40">
  <section class="copyright pb-30">
    <div class="container">
      <div class="col-md-6">
        <p class="text-left">Copyright &copy; <b>Venga</b> 2017. All Rights Reserved.</p>
      </div>
      <div class="col-md-6">
        <ul class="social text-right">
          <li><a target="_blank" href="https://www.instagram.com/_venga/"><i class="fa fa-instagram"></i></a></li>
          <li><a target="_blank" href="https://www.facebook.com/bevenga/"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </section>
</footer>

app/views/trainers/index.html.erb
    <!-- Search Overlay Menu -->
    <div class="search-overlay-menu">
        <span class="search-overlay-close"><i class="ion ion-ios-close-empty"></i></span>
        <form role="search" id="searchform" action="/search" method="get">
            <input value="" name="q" type="search" placeholder="Search..." />
            <button type="submit"><i class="ion ion-ios-search"></i></button>
        </form>
    </div>
    <!-- End Search Overlay Menu -->


    <!-- Site Wraper -->
    <div class="wrapper">

        <!-- HEADER -->
        <header id="header" class="header">
            <div class="container">

                <!-- Logo -->
                <div class="logo">
                   <%= link_to root_path do %>
                  <img src="http://res.cloudinary.com/dskagnrtl/image/upload/v1489412008/Logo-Venga1_copy_rl9xio.png" class="logo-white" alt="Venga" id="logo1"</>

                  <img src="http://res.cloudinary.com/dskagnrtl/image/upload/v1489412184/Logo-Venga3_copy_djvzm2.png" class="logo-dark" alt="Venga" id="logo2"</>
                  <% end %>
                </div>
                <!-- End Logo -->
            </div>
        </header>

        <!-- CONTENT --------------------------------------------------------------------------------->
        <!-- Intro Section -->
        <section id="intro">
          <div class="flexslider fullscreen-carousel hero-slider-1 ">
            <ul class="slides">

              <!--Slide-->

              <div class="slide-bg-image overlay-dark parallax parallax-section1" data-background-img="http://res.cloudinary.com/dskagnrtl/image/upload/v1489392395/banner1_copy_mx7gcd.jpg">
                <div class="js-Slide-fullscreen-height container">
                  <div class="intro-content">
                    <div class="intro-content-inner">
                      <h2 class="h2">Welcome Vengy</h2>
                    </div>
                  </div>
                </div>
              </div>

            </ul>
          </div>
        </section>
        <!-- End Intro Section -->

        <section id="elements" class="section-padding ptb ptb-sm-80">
          <div class="container text-center">
            <h3 class="page-title">Vos coachs sportifs</h3>
          </div>
          <div class="container">
            <div class="tabs-cont">

              <div id="tab-cover-box" class="tab-pane active">
                <div class="container">
                  <div class="row">
                  <% @trainers.each do |trainer| %>
                    <div class="col-md-4">
                      <div class="cover-box mb-30">
                        <figure class="cover-box-img">
                          <%= cl_image_tag trainer.photo, alt:"cover-img" %>
                        </figure>
                        <div class="cover-box-content">
                          <h5><%= trainer.surname %> <%= trainer.name %></h5>
                          <p><%= trainer.description.first(100) %>...</p>
                          <%= link_to 'Read More', trainer_path(trainer), class:"link fa fa-angle-right right" %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </section>



        <!-- Scroll Top -->
        <a class="scroll-top">
            <i class="fa fa-angle-double-up"></i>
        </a>
        <!-- End Scroll Top -->

    </div>
    <!-- Site Wraper End -->

app/views/trainers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for(@trainer) do |f| %>
      <%= f.input :city %>
      <%= f.input :description %>
      <%= f.input :email %>
      <%= f.input :phone %>
      <%= f.input :name %>
      <%= f.input :surname %>
      <%= f.input :specialities %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/trainers/show.html.erb
    <!-- Search Overlay Menu -->
    <div class="search-overlay-menu">
        <span class="search-overlay-close"><i class="ion ion-ios-close-empty"></i></span>
        <form role="search" id="searchform" action="/search" method="get">
            <input value="" name="q" type="search" placeholder="Search..." />
            <button type="submit"><i class="ion ion-ios-search"></i></button>
        </form>
    </div>
    <!-- End Search Overlay Menu -->


    <!-- Site Wraper -->
    <div class="wrapper">

        <!-- Header -->
        <header id="header" class="header header-light">
            <div class="container header-inner">

                <!-- Logo -->
                <div class="logo">
                  <%= link_to root_path do %>
                  <img src="http://res.cloudinary.com/dskagnrtl/image/upload/v1489412008/Logo-Venga1_copy_rl9xio.png" class="logo-white" alt="Venga" id="logo1"</>

                  <img src="http://res.cloudinary.com/dskagnrtl/image/upload/v1489412184/Logo-Venga3_copy_djvzm2.png" class="logo-dark" alt="Venga" id="logo2"</>
                  <% end %>
                </div>
                <!-- End Logo -->
            </div>
        </header>
        <!-- End Header -->

        <!-- CONTENT --------------------------------------------------------------------------------->

<!-- Team Slider Section -->

<section class="ptb ptb-sm-80">
  <div class="container">
    <div class="row text-center">
      <h3><%= @trainer.surname%> <%= @trainer.name %></h3>
    </div>
    <div class="spacer-60"></div>
    <div class="row">
      <!-- Team Slider -->


        <div class="col-md-4">
          <div class="team-item nf-col-padding">
            <div class="team-item-img">
              <%= cl_image_tag @trainer.photo %>
            </div>
          </div>
        </div>

        <div class="col-md-8">
          <p class="lead"><%= @trainer.description %></p>
          <br>
          <p><i class="fa fa-map-marker" aria-hidden="true"></i> <%= @trainer.address %></p>
          <br>
          <p class="lead dark"><%= @trainer.email %></p>
          <p class="lead dark"><%= @trainer.phone %></p>
          <br>
          <div class="sidebar-widget">
            <h5>Specialités</h5>
            <hr />
            <ul class="widget-tag">
              <% @liste.each do |specialite|%>
              <li><a><%= specialite%></a></li>
              <% end %>
            </ul>
          </div>
        </div>


    </div>
  </div>
</section>

        <!-- Pricing Table Section -->
        <section class="ptb ptb-sm-80">
            <div class="container text-center">
                <div class="spacer-60"></div>
                <div class="row">
                <% @trainer.offers.each do |offer| %>
                    <div class="col-md-4 mb-30">
                        <div class="Pricing-box">
                            <div class="pricing-features spacing-grid">
                                <p><%= offer.description %></p>
                            </div>
                            <hr>
                            <div class="spacing-box">
                              <div class="price"><span class="price-sm">€</span><span class="price-lg"><%= offer.price %></span></div>
                              <div class="price-tenure">per <%= offer.frequency %></div>
                            </div>
                            <hr />
                        </div>
                    </div>
                  <% end %>
                </div>
                <div class="spacer-30"></div>
            </div>
        </section>

        <!-- End Pricing Table Section -->

        <!-- Testimonials -->
        <section id="testimonial" class="overlay-dark80 dark-bg ptb ptb-sm-80" style="background-image: url('img/full/25.jpg');" data-stellar-background-ratio="0.4">
          <div class="container">
            <div class="owl-carousel testimonial-carousel nf-carousel-theme white">
              <% @trainer.reviews.each do |review| %>
              <div class="item">
                <div class="testimonial text-center dark-color">
                  <div class="container-icon"><i class="fa fa-quote-right"></i></div>
                  <p class="lead">" <%= review.description %>"</p>
                  <h6 class="quote-author"><%= review.client_name %></h6>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </section>
        <!-- End Testimonials -->

        <!-- End CONTENT ------------------------------------------------------------------------------>




        <!-- Scroll Top -->
        <a class="scroll-top">
            <i class="fa fa-angle-double-up"></i>
        </a>
        <!-- End Scroll Top -->

    </div>
    <!-- Site Wraper End -->